# This is a basic workflow to help you get started with Actions

name: Publish

on:
  push:
    tags:        
      - '**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Package and release
        uses: BigWigsMods/packager@v2
